### ISSUE TITLE
Migrate `LaunchDarklyConfigStore` to `@configu/integrations`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#519] opened 2024-10-09 11:36 UTC
### Suggestion

Migrate the `LaunchDarklyConfigStore` from its current setup to the new `@configu/integrations` module as part of the major restructuring. The goal is to move all third-party integrations, including stores, expressions, and libraries, to `@configu/integrations`.

### Motivation

This migration is part of a larger effort to better organize and modularize the product. Moving the `LaunchDarklyConfigStore` will align with the new structure, making the system cleaner and more maintainable.

### Context

You can refer to the already migrated stores for guidance:  
[Migrated stores in integrations](https://github.com/configu/configu/tree/main/packages/integrations/stores).

Base stores implementations from `@configu/ts` can be found here:  
[Base stores in TS](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/ts/src/stores).

The old node-based stores were previously in `@configu/node`:  
[Node stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/node/src/stores).

The old browser-based stores were previously in `@configu/browser`:  
[Browser stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/browser/src/stores).

**Comment by ezhil56x** [comment] 2024-10-10 09:56
I would like to work on this. Can I get this assigned?
Thanks!

**Comment by RichardAkman** [comment] 2024-10-10 10:05
All yours @ezhil56x

**Comment by su-shubham** [comment] 2024-10-13 07:34
Interested! @rannn505 @RichardAkman

**Comment by RichardAkman** [comment] 2024-10-13 07:37
> Interested! @rannn505 @RichardAkman

We appreciate your enthusiasm @su-shubham but the issue is currently assigned to @ezhil56x. You can browse other unassigned issues that pique your interest.

**Comment by ezhil56x** [comment] 2024-10-17 12:44
@RichardAkman Dropping this. Kindly assign to someone else

**Comment by SanchitMahajan236** [comment] 2024-10-18 05:03
Hey @RichardAkman , Please assign me this issue. I would love to contribute.

**Comment by RichardAkman** [comment] 2024-10-18 12:56
All yours @SanchitMahajan236

**Comment by TomerPacific** [comment] 2024-10-21 17:16
@RichardAkman - While I am aware this issue was recently assigned, just wanted to mention that I am willing to assist here if @SanchitMahajan236 decides to drop the issue.

**Comment by TomerPacific** [comment] 2024-10-27 11:58
@RichardAkman - Seeing as @SanchitMahajan236 is inactive for over a week, can this issue be assigned to me? I have a PR ready.

**Comment by RichardAkman** [comment] 2024-10-27 12:03
You are correct @TomerPacific, you got it. @SanchitMahajan236, please feel free to pick another issue for contribution, we appreciate your willingness to contribute 🙏🏻

**Comment by SanchitMahajan236** [comment] 2024-10-27 13:34
I was working on the issue just now and when I opened the assigned issues section to see the issue number, I found that I have been unassigned. 
I apologize for the delay on my end but I think you should have atleast left a message asking if I am working on the issue @RichardAkman.

**Comment by RichardAkman** [comment] 2024-10-27 13:38
@SanchitMahajan236, thanks for letting me know. I understand the frustration, and I apologize for any miscommunication. We aim to keep issues moving smoothly, so if there’s no update or opened PRs after some time, we may reassign to help other contributors get involved. In the future, feel free to comment on the issue or open a draft PR if you're still actively working on it; this helps us stay aligned on progress. Your contributions are valued, and I appreciate your understanding. Let’s keep up the good collaboration!

**Comment by SanchitMahajan236** [comment] 2024-10-27 15:16
I will definitely remember your advice.

**Closed** 2024-10-28 07:55 UTC
Labels: feat, good first issue
